### ISSUE TITLE
Problem with Redemption

### ISSUE THREAD

**Issue by ghost** [BramscoChill/WLMToPstConverter#1]
Is anywhere video how to install Redemption into this or how to compile this program, because when I'm trying to convert I have errors.

**Comment by hazsmix** [comment]
@SeboPG 
You need to download Redemption as it is an external dependency. Note that it is a licenced program for commercial use.
http://dimastr.com/redemption/download.htm
Then drop all the files in the zip into the ExternalFiles folder of the project.
Visual Studio should then be able to run.
